// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:fe653a29-c935-45ac-8d79-282400dfe9f1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Jk6fDqRhH",
    "aws_user_pools_web_client_id": "2h4363or7u2322k4bvtr1q82m",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://w2l7vjr5krekxiabs4x6s4uzgi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "fypf40655550f734416ad5792927d59a53e-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "XR": {
        "scenes": {
            "homepagescene": {
                "sceneConfig": {
                    "sceneId": "0ef6a5810f964ec6bebdee28cde0055e.scene",
                    "region": "us-east-1",
                    "projectName": "Drafts-user/ryan_lee",
                    "url": "https://sumerian.us-east-1.amazonaws.com/20180801/projects/Drafts-user%2Fryan_lee/release/authTokens?sceneId=0ef6a5810f964ec6bebdee28cde0055e.scene"
                }
            }
        }
    },
    "predictions": {
        "identify": {
            "identifyEntities": {
                "proxy": false,
                "region": "us-east-1",
                "celebrityDetectionEnabled": true,
                "defaults": {
                    "collectionId": "identifyEntitiesd06785fa-dev",
                    "maxEntities": 50
                }
            }
        }
    }
};


export default awsmobile;
